//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarburantCoutUnitaire
    {
        public int IdCoutUnitaireCarburant { get; set; }
        public int Code_refCarburant { get; set; }
        public Nullable<decimal> CoutUnitaireCarburant { get; set; }
        public System.DateTime DateChangementTarif { get; set; }
    }
}
