//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carburant
    {
        public int IdCarburant { get; set; }
        public int ClientId { get; set; }
        public int VehiculeId { get; set; }
        public string Description { get; set; }
        public System.DateTime DateCarburant { get; set; }
        public decimal QuantiteCarburant { get; set; }
        public decimal CoutUnitaireCarburant { get; set; }
        public Nullable<int> FournisseurId { get; set; }
        public Nullable<int> KilometrageDebut { get; set; }
        public Nullable<int> KilometrageFin { get; set; }
        public string NoteCarburant { get; set; }
        public Nullable<decimal> CoutTotal { get; set; }
    }
}
