//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int IdClient { get; set; }
        public string NomClient { get; set; }
        public string AdresseClient { get; set; }
        public string VilleClient { get; set; }
        public string CodePostalClient { get; set; }
        public string ContactClient { get; set; }
        public string Tel1Client { get; set; }
        public string Tel2Client { get; set; }
        public string FaxClient { get; set; }
        public string SiteWebClient { get; set; }
        public string EmailClient { get; set; }
        public string GisParametres { get; set; }
    }
}
