//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPA.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccessRight> AccessRights { get; set; }
        public virtual DbSet<AccessRightDepartement> AccessRightDepartements { get; set; }
        public virtual DbSet<AlerteEmail> AlerteEmails { get; set; }
        public virtual DbSet<Carburant> Carburants { get; set; }
        public virtual DbSet<CarburantCoutUnitaire> CarburantCoutUnitaires { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Depense> Depenses { get; set; }
        public virtual DbSet<Entretien> Entretiens { get; set; }
        public virtual DbSet<EntretienMaitre> EntretienMaitres { get; set; }
        public virtual DbSet<EntretienProgramme> EntretienProgrammes { get; set; }
        public virtual DbSet<Fournisseur> Fournisseurs { get; set; }
        public virtual DbSet<GIS_GPA> GIS_GPA { get; set; }
        public virtual DbSet<GISLastUpdate> GISLastUpdates { get; set; }
        public virtual DbSet<HISTORIQUE_CONNEXION> HISTORIQUE_CONNEXION { get; set; }
        public virtual DbSet<LectureKilometrage> LectureKilometrages { get; set; }
        public virtual DbSet<Parametre> Parametres { get; set; }
        public virtual DbSet<Piece> Pieces { get; set; }
        public virtual DbSet<REFERENTIEL> REFERENTIELs { get; set; }
        public virtual DbSet<Reparation> Reparations { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<TYPE_REFERENTIEL> TYPE_REFERENTIEL { get; set; }
        public virtual DbSet<Utilisateur> Utilisateurs { get; set; }
        public virtual DbSet<Vehicule> Vehicules { get; set; }
        public virtual DbSet<VehiculeAcquisition> VehiculeAcquisitions { get; set; }
        public virtual DbSet<VehiculeAcquisitionPaiement> VehiculeAcquisitionPaiements { get; set; }
        public virtual DbSet<VehiculeConducteur> VehiculeConducteurs { get; set; }
        public virtual DbSet<VehiculeDepartement> VehiculeDepartements { get; set; }
        public virtual DbSet<VehiculeDocument> VehiculeDocuments { get; set; }
        public virtual DbSet<VehiculeModele> VehiculeModeles { get; set; }
        public virtual DbSet<ModeleC100KM> ModeleC100KM { get; set; }
        public virtual DbSet<KilometrageMensuel> KilometrageMensuels { get; set; }
        public virtual DbSet<DepensesClient> DepensesClients { get; set; }
        public virtual DbSet<ParametresDepens> ParametresDepenses { get; set; }
    }
}
