//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Depense
    {
        public int IdDepense { get; set; }
        public int TypeId { get; set; }
        public Nullable<int> EntretienId { get; set; }
        public Nullable<int> ReparationId { get; set; }
        public decimal QuantiteDepense { get; set; }
        public decimal CoutUnitaireDepense { get; set; }
        public Nullable<int> PieceId { get; set; }
        public Nullable<System.DateTime> ExpirationGarantie { get; set; }
        public string Description { get; set; }
        public string NoteDepense { get; set; }
    }
}
