//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntretienMaitre
    {
        public int IdEntretienMaitre { get; set; }
        public int ClientId { get; set; }
        public string DescriptionEntretienMaitre { get; set; }
        public Nullable<int> RepeterNb { get; set; }
        public Nullable<int> RepeterPeriode { get; set; }
        public Nullable<int> RepeterKilometrage { get; set; }
        public Nullable<int> RappelNb { get; set; }
        public Nullable<int> RappelPeriode { get; set; }
        public Nullable<int> RappelKilometrage { get; set; }
    }
}
