//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fournisseur
    {
        public int IdFournisseur { get; set; }
        public int ClientId { get; set; }
        public int TypeFournisseur { get; set; }
        public string NomFournisseur { get; set; }
        public string AdresseFournisseur { get; set; }
        public string VilleFournisseur { get; set; }
        public string CodePostalFournisseur { get; set; }
        public string ContactFournisseur { get; set; }
        public string Tel1Fournisseur { get; set; }
        public string Tel2Fournisseur { get; set; }
        public string FaxFournisseur { get; set; }
        public string SiteWebFournisseur { get; set; }
        public string EmailFournisseur { get; set; }
    }
}
