//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametre
    {
        public int ParameterId { get; set; }
        public string KeyWord { get; set; }
        public string Value { get; set; }
        public string Description { get; set; }
    }
}
