//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Piece
    {
        public int IdPiece { get; set; }
        public int ClientId { get; set; }
        public string NumeroPiece { get; set; }
        public string NomPiece { get; set; }
        public decimal PrixPiece { get; set; }
        public System.DateTime DatePrixPiece { get; set; }
        public Nullable<int> FournisseurId { get; set; }
        public string Constructeur { get; set; }
    }
}
