//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class REFERENTIEL
    {
        public int ID_REFERENTIELS { get; set; }
        public string KEY_REF { get; set; }
        public int CODE_REF { get; set; }
        public string VALUE { get; set; }
    }
}
