//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reparation
    {
        public int IdReparation { get; set; }
        public int ClientId { get; set; }
        public int VehiculeId { get; set; }
        public System.DateTime DateReparation { get; set; }
        public System.DateTime DateMiseService { get; set; }
        public decimal HeuresArret { get; set; }
        public Nullable<int> FournisseurId { get; set; }
        public string DescriptionReparation { get; set; }
        public decimal CoutReparation { get; set; }
        public Nullable<int> KilometrageReparation { get; set; }
        public string NoteReparation { get; set; }
    }
}
