//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public int IdRole { get; set; }
        public string NomRole { get; set; }
        public string DescriptionRole { get; set; }
        public Nullable<int> ProfileRole { get; set; }
    }
}
