//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicule
    {
        public int IdVehicule { get; set; }
        public int ClientId { get; set; }
        public string MatriculeVehicule { get; set; }
        public string CouleurVehicule { get; set; }
        public string NumeroSerieVehicule { get; set; }
        public Nullable<System.DateTime> MiseCirculation { get; set; }
        public Nullable<int> TypeCarburantId { get; set; }
        public Nullable<int> TypeVehiculeId { get; set; }
        public Nullable<int> DepartementId { get; set; }
        public Nullable<int> ConducteurId { get; set; }
        public bool IsActif { get; set; }
        public Nullable<int> codeRefMarque { get; set; }
        public Nullable<int> IdModele { get; set; }
    }
}
