//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehiculeAcquisitionPaiement
    {
        public int IdPaiement { get; set; }
        public int AcquisitionId { get; set; }
        public string ReferencePaiement { get; set; }
        public System.DateTime DatePaiement { get; set; }
        public decimal MontantPaiement { get; set; }
        public string NotePaiement { get; set; }
    }
}
