//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehiculeDepartement
    {
        public int IdDepartement { get; set; }
        public int ClientId { get; set; }
        public string NomDepartement { get; set; }
        public Nullable<int> code { get; set; }
    }
}
