//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehiculeConducteur
    {
        public int IdConducteur { get; set; }
        public int ClientId { get; set; }
        public string NomConducteur { get; set; }
        public string PrenomConducteur { get; set; }
        public Nullable<System.DateTime> DateNaissanceConducteur { get; set; }
        public Nullable<System.DateTime> DateEmbaucheConducteur { get; set; }
        public string NumeroPermisConducteur { get; set; }
        public string AdresseConducteur { get; set; }
        public string VilleConducteur { get; set; }
        public string CodePostalConducteur { get; set; }
        public string Tel1Conducteur { get; set; }
        public string Tel2Conducteur { get; set; }
        public string EmailConducteur { get; set; }
    }
}
